---
- hosts: all
  sudo: yes
  gather_facts: yes
  tasks:
    - name: install libselinux
      yum: name=libselinux-python state=present
      tags: libselinux-python
      
    - name: Add db.intermundomedia.com to hosts file
      lineinfile: dest=/etc/hosts line='127.0.0.1 db.intermundomedia.com' state=present
