---

  - name: Create Vagrant sandbox
    command: /bin/mv -i /var/www /vagrant/sandbox
    args:
      creates: /vagrant/sandbox

  - name: Create /var/www/ as symlink to Vagrant sandbox
    command: /bin/ln -s /vagrant/sandbox /var/www
    
  - name: install packages
    yum: name={{ item }} state=present
    with_items: packages
    tags: package

  - name: Copy httpd.conf
    copy: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf

  - name: Download Zend Guard Loader Tarball
    command: /usr/bin/wget http://brutebyte.com/modules/{{ zend_tarball }}
    args:
      chdir: /tmp
      creates: /tmp/{{ zend_tarball }}

  - name: Untar Zend Guard Loader
    command: /bin/tar -zxvf {{ zend_tarball }}
    args:
      chdir: /tmp

  - name: Install Zend Guard Loader Module
    command: /bin/cp /tmp/{{ zend_loader }}/php-5.4.x/ZendGuardLoader.so /usr/lib64/php/modules/

  - name: Copy php.ini
    copy: src=php.ini.j2 dest=/etc/php.ini

  - name: Create secure directory for smarty templates
    command: /bin/mkdir -p /usr/local/secure
    args:
      creates: /usr/local/secure

  - name: Configure secure template directory permissions
    command: "{{ item }}"
    with_items:
      - /bin/chown -R :apache /usr/local/secure
      - /bin/chmod -R 775 /usr/local/secure

  - name: Copy index.html
    template: src=index.html.j2 dest={{ apache_docroot }}/index.html

  - name: start and enable the httpd service
    service: name={{ apache_service }} state=started enabled=yes
    tags: service
